/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CamerasIndexRouteImport } from './routes/cameras/index'
import { Route as CamerasCameraIdRouteImport } from './routes/cameras/$cameraId'

const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasIndexRoute = CamerasIndexRouteImport.update({
  id: '/cameras/',
  path: '/cameras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasCameraIdRoute = CamerasCameraIdRouteImport.update({
  id: '/cameras/$cameraId',
  path: '/cameras/$cameraId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/recordings': typeof RecordingsRoute
  '/cameras/$cameraId': typeof CamerasCameraIdRoute
  '/cameras/': typeof CamerasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/recordings': typeof RecordingsRoute
  '/cameras/$cameraId': typeof CamerasCameraIdRoute
  '/cameras': typeof CamerasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/recordings': typeof RecordingsRoute
  '/cameras/$cameraId': typeof CamerasCameraIdRoute
  '/cameras/': typeof CamerasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/recordings'
    | '/cameras/$cameraId'
    | '/cameras/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/recordings' | '/cameras/$cameraId' | '/cameras'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/recordings'
    | '/cameras/$cameraId'
    | '/cameras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  RecordingsRoute: typeof RecordingsRoute
  CamerasCameraIdRoute: typeof CamerasCameraIdRoute
  CamerasIndexRoute: typeof CamerasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/': {
      id: '/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof CamerasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/$cameraId': {
      id: '/cameras/$cameraId'
      path: '/cameras/$cameraId'
      fullPath: '/cameras/$cameraId'
      preLoaderRoute: typeof CamerasCameraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  RecordingsRoute: RecordingsRoute,
  CamerasCameraIdRoute: CamerasCameraIdRoute,
  CamerasIndexRoute: CamerasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
